### ISSUE TITLE
Taxonomy Map

### ISSUE THREAD

**Issue by StephenCataldo** [StephenCataldo/comment-better#16]
One of the cards should be a taxonomy map:

(rough notes here)

Active Listening
RCC Cycle / NVC / Powerful NDC / CP Cycle
Steelman 
Reject Trolls from the Center
Expand Overton Window
Share (and others): 
Share:Choose your metaphor
Share:Choose your cascade start-point
 

Open: Reflect
Open: Agreement
Open: Can you talk more about...
Open: Question, or Question: Question, er um
Open/Question: Can you talk more about what you mean by _________.

**Comment by ktfleeman** [comment]
Closing in favor of: https://github.com/StephenCataldo/comment-better/issues/12 

I've put @StephenCataldo 's notes in the Content Google doc: https://docs.google.com/document/d/1n738ZPmnxg-k74o0PqOQTyoKNKW_z7aVkrGeUD65iUY/edit#
