### ISSUE TITLE
new system fails to close

### ISSUE THREAD

**Issue by StephenCataldo** [StephenCataldo/comment-better#6]
modal fails to close.

**Comment by StephenCataldo** [comment]
The modal [the main window] that opens when you hit the orange cbbutton doesn't close at the right times.  This needs more careful testing (which anyone can do and add here), perhaps a mix of UX and testing to see simply if it does what you think it should do as a user. Also, the escape key should close the modal, I think. The modal is react, but this issue is at the intersection of our basic jquery/javascript interactions with facebook which then open the react modal. Figuring out and cleaning up what we did at the hackathon, even if it isn't a fix, is a start!

**Comment by GetHub91** [comment]
Modal now closes when comment better button, text box, or any part of the window outside the modal are pressed. When blank space inside the modal is pressed, nothing happens.
